include theos/makefiles/common.mk

TOOL_NAME = unboxd
unboxd_FILES = ../UBDelegate.m ../UBServer.m
unboxd_PRIVATE_FRAMEWORKS = AppSupport
unboxd_INSTALL_PATH = /usr/libexec

include $(THEOS_MAKE_PATH)/tool.mk
